version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: travel_postgres
    environment:
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_pass
      POSTGRES_DB: travel_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: travel_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@travel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres